LABELS = {
    1 : 'Alfa Romeo',
    2 : 'Aston Martin',
    3 : 'Audi',
    4 : 'Bentley',
    5 : 'BMW',
    6 : 'Citroen',
    7 : 'Cupra',
    8 : 'Dacia',
    9 : 'Daewoo',
    10 : 'Dodge',
    11 : 'Fiat',
    12 : 'Ford',
    13 : 'Honda',
    14 : 'Hyundai',
    15 : 'Jaguar',
    16 : 'Jeep',
    17 : 'Kia',
    18 : 'Land Rover',
    19 : 'Lexus',
    20 : 'Maserati',
    21 : 'Mazda',
    22 : 'Mercedes Benz',
    23 : 'MG',
    24 : 'MiniCopper',
    25 : 'Mitsubishi',
    26 : 'Nissan',
    27 : 'Peugeot',
    28 : 'Porsche',
    29 : 'Renault',
    30 : 'Seat',
    31 : 'Skoda',
    32 : 'Smart',
    33 : 'Subaru',
    34 : 'Suzuki',
    35 : 'Tesla',
    36 : 'Toyota',
    37 : 'Vauxhall',
    38 : 'Volvo',
    39 : 'VW',
    40 : 'Marvel', 
}